<a href="https://colab.research.google.com/github/Aidi379/Python_fundamental/blob/main/17.%20DataFrames_Concatenation_and_Merging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Pandas is a data manipulation and analysis tool that uses a data structure known as DataFrame.
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows & columns).
# Import Pandas Library into the current environment
# "pd" is an alias of "Pandas"
import pandas as pd

In [2]:
# Read the first excel sheet into a Pandas DataFrame
from google.colab import files
uploaded = files.upload()
investor_1_df = pd.read_csv('investors_group_1.csv')
investor_1_df

Saving investors_group_1.csv to investors_group_1.csv

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,A1,Ryan,David,32,80100,5,aggressive,buy house
1,A2,Sherif,George,54,950000,30,conservative,retire
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education
3,A4,Victoria,Keller,43,300901,3,moderate,investment property
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans
5,A6,Bassel,Nasr,50,401201,15,conservative,retire
6,A7,Chris,Peter,38,352000,8,moderate,kids education
7,A8,Nancy,Smith,55,900000,17,conservative,retire
8,A9,Heidi,Smith,23,1500,1,moderate,retire early

In [4]:
# Read the second excel sheet into a Pandas DataFrame
uploaded = files.upload()
investor_2_df = pd.read_csv('investors_group_2.csv')
investor_2_df

Saving investors_group_2.csv to investors_group_2.csv

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,B1,Paul,McDermid,31,70205,6,aggressive,buy house
1,B2,Steve,Mitchelle,55,990000,28,conservative,retire
2,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans
3,B4,Mohamed,Aly,43,38000,3,moderate,investment property
4,B5,Salma,Smith,22,3000,2,aggressive,pay student loans

In [5]:
# Let's concatenate both dataframes #1 and #2
investor_df_combined = pd.concat([investor_1_df, investor_2_df])
investor_df_combined

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,A1,Ryan,David,32,80100,5,aggressive,buy house
1,A2,Sherif,George,54,950000,30,conservative,retire
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education
3,A4,Victoria,Keller,43,300901,3,moderate,investment property
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans
5,A6,Bassel,Nasr,50,401201,15,conservative,retire
6,A7,Chris,Peter,38,352000,8,moderate,kids education
7,A8,Nancy,Smith,55,900000,17,conservative,retire
8,A9,Heidi,Smith,23,1500,1,moderate,retire early
0,B1,Paul,McDermid,31,70205,6,aggressive,buy house
1,B2,Steve,Mitchelle,55,990000,28,conservative,retire
2,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans
3,B4,Mohamed,Aly,43,38000,3,moderate,investment property
4,B5,Salma,Smith,22,3000,2,aggressive,pay student loans

In [6]:
# Note that index need to be reset, you can achieve this using df.reset_index()
# drop = True is used to drop the index column after reset_index() operation is performed
investor_df_combined.reset_index(drop = True)

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,A1,Ryan,David,32,80100,5,aggressive,buy house
1,A2,Sherif,George,54,950000,30,conservative,retire
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education
3,A4,Victoria,Keller,43,300901,3,moderate,investment property
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans
5,A6,Bassel,Nasr,50,401201,15,conservative,retire
6,A7,Chris,Peter,38,352000,8,moderate,kids education
7,A8,Nancy,Smith,55,900000,17,conservative,retire
8,A9,Heidi,Smith,23,1500,1,moderate,retire early
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans

In [8]:
# Let's assume we acquired new information such as investors salaries and job titles
uploaded = files.upload()
investor_new_df = pd.read_csv('investors_new_information.csv')
investor_new_df

Saving investors_new_information.csv to investors_new_information.csv

   Investor ID  Salary             Job Title
0           A1   90000              engineer
1           A2  283000  engineering director
2           A3  150000       product manager
3           A4  175000        medical doctor
4           A5   75000                 nurse
5           A6  135000            Pharmacist
6           A7  125000               plumber
7           A8  198000        senior manager
8           A9   45000               teacher
9           B1   89000               manager
10          B2   25000       dental hygenist
11          B3  136000               dentist
12          B4  145000             professor
13          B5   35000   construction worker

In [22]:
# Let's merge data on 'Investor ID'
investor_df = pd.merge(investor_df_combined, investor_new_df, on = 'Investor ID')
investor_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker

**PRACTICE OPPORTUNITY:**
- **Assume that you became a new client to the investment firm that has its data stored in "investor_df", write a python code that performs the following:**
    - **1. Define a new Pandas DataFrame named "new_client_df" that contains your information such as client ID (choose C1), first name, last name, age, portfolio size, years with investment firm, risk tolerance, goal, salaries and job title**
    - **2. Concatenate this new dataframe to the original Pandas dataframe "investor_df"**
    - **3. Reset the index**

In [23]:
investor_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker

In [28]:
new_client = {
    'Investor ID': ['C1'],
    'First Name': ['Aidi'],
    'Last Name': ['Su'],
    'Age': [28],
    'Portfolio Size' : [24500],
    'Years with Investment Firm': [5],
    'Risk Tolerance' : ['moderate'],
    'Goal' : ['investment property'],
    'Salary' : [70000],
    'Job Title':['product manager']
    }
new_client_df = pd.DataFrame(d)
new_client_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,C1,Aidi,Su,28,24500,5,moderate,investment property,70000,product manager

In [34]:
investor_concat_df = pd.concat([investor_df, new_client_df])
investor_concat_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker
0,C1,Aidi,Su,28,24500,5,moderate,investment property,70000,product manager

In [31]:
investor_concat_df = investor_concat_df.reset_index()
investor_concat_df

,index,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker
14,0,C1,Aidi,Su,28,24500,5,moderate,investment property,70000,product manager

In [35]:
investor_concat_df = investor_concat_df.reset_index(drop= True)
investor_concat_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker
14,C1,Aidi,Su,28,24500,5,moderate,investment property,70000,product manager

# PRACTICE OPPORTUNITY SOLUTION

**PRACTICE OPPORTUNITY SOLUTION:**
- **Assume that you became a new client to the investment firm that has its data stored in "investor_df", write a python code that performs the following:**
    - **1. Define a new Pandas DataFrame named "new_client_df" that contains your information such as client ID (choose C1), first name, last name, age, portfolio size, years with investment firm, risk tolerance, goal, salaries and job title**
    - **2. Concatenate this new dataframe to the original Pandas dataframe "investor_df"**
    - **3. Reset the index**

In [ ]:
investor_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker

In [ ]:
new_client = {
        'Investor ID': ['C1'],
        'First Name': ['Ryan'],
        'Last Name': ['Ahmed'],
        'Age': [33],
        'Portfolio Size': [30000],
        'Years with Investment Firm': [12],
        'Risk Tolerance': ['aggressive'],
        'Goal': ['retire early'],
        'Salary': [75000],
        'Job Title': ['professor']}
new_client_df = pd.DataFrame(new_client)
new_client_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,C1,Ryan,Ahmed,33,30000,12,aggressive,retire early,75000,professor

In [ ]:
investor_df = pd.concat([investor_df, new_client_df], axis = 0)
investor_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker
0,C1,Ryan,Ahmed,33,30000,12,aggressive,retire early,75000,professor

In [ ]:
# Note that index need to be reset, you can achieve this using df.reset_index()
investor_df.reset_index(drop = True)

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker
14,C1,Ryan,Ahmed,33,30000,12,aggressive,retire early,75000,professor

# EXCELLENT JOB!